# Generated by Django 2.0.6 on 2018-06-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='comment',
            field=models.CharField(default='no comment', max_length=1000),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(default='title', max_length=300),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.CharField(default='none', max_length=4),
        ),
    ]
